---
services:
  asr:
    build:
      context: .
    # image: ghcr.io/searchandrescuegg/asr:v1.1.0
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
